/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;


import patterns.Singleton;
import database.SQLite;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;


/**
 *
 * @author Baxi
 */
public class WindowsMenu extends javax.swing.JFrame {

    
    public WindowsMenu() {
        initComponents();
        this.setSize(800,600);
        setLocationRelativeTo(null);
        cerrarPaneles();
        updateTable();
        cargarDatosListas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonProfesores = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonCursos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonAulas = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonImparte = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButtonDisponibilidad = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButtonHorario = new javax.swing.JButton();
        jPanelHorarios = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableCursosHorario = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jButtonConfirmBill8 = new javax.swing.JButton();
        jButtonConfirmBill9 = new javax.swing.JButton();
        CD_Cliente5 = new javax.swing.JLabel();
        jButtonClose6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanelProfesor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableProfesor = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButtonConfirmBill4 = new javax.swing.JButton();
        jButtonConfirmBill5 = new javax.swing.JButton();
        CD_Cliente = new javax.swing.JLabel();
        jButtonClose1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelCursos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCursos = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButtonConfirmBill6 = new javax.swing.JButton();
        jButtonConfirmBill7 = new javax.swing.JButton();
        CD_Cliente1 = new javax.swing.JLabel();
        jButtonClose2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanelAulas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAulas = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jButtonEliminarAula = new javax.swing.JButton();
        jButtonAgregarAula = new javax.swing.JButton();
        CD_Cliente2 = new javax.swing.JLabel();
        jButtonClose3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanelImparte = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableImparte = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jButtonEliminarRelacion = new javax.swing.JButton();
        jButtonAgregarRelacion = new javax.swing.JButton();
        CD_Cliente3 = new javax.swing.JLabel();
        jButtonClose4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanelDisponibilidad = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableDisponibilidad = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButtonEliminarRelacionDisponibilidad = new javax.swing.JButton();
        jButtonAgregarRelacionDisponibilidad = new javax.swing.JButton();
        CD_Cliente4 = new javax.swing.JLabel();
        jButtonClose5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButtonOff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelLogin.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), java.awt.Color.white));
        jPanelLogin.setToolTipText("");
        jPanelLogin.setAlignmentX(0.0F);
        jPanelLogin.setAlignmentY(0.0F);
        jPanelLogin.setMaximumSize(new java.awt.Dimension(265, 600));
        jPanelLogin.setMinimumSize(new java.awt.Dimension(265, 600));
        jPanelLogin.setName("panelLogin"); // NOI18N
        jPanelLogin.setPreferredSize(new java.awt.Dimension(265, 600));
        jPanelLogin.setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(153, 148, 148));
        jLabelTitulo.setText("Guía de Horarios");
        jLabelTitulo.setToolTipText("");
        jPanelLogin.add(jLabelTitulo);
        jLabelTitulo.setBounds(20, 30, 230, 33);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Profesores");
        jLabel5.setToolTipText("");
        jPanelLogin.add(jLabel5);
        jLabel5.setBounds(20, 140, 170, 28);

        jButtonProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonProfesores.setBorder(null);
        jButtonProfesores.setBorderPainted(false);
        jButtonProfesores.setContentAreaFilled(false);
        jButtonProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonProfesores.setRequestFocusEnabled(false);
        jButtonProfesores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonProfesores.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonProfesores.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProfesoresMouseClicked(evt);
            }
        });
        jButtonProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfesoresActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonProfesores);
        jButtonProfesores.setBounds(200, 120, 60, 60);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cursos");
        jLabel4.setToolTipText("");
        jPanelLogin.add(jLabel4);
        jLabel4.setBounds(20, 200, 170, 28);

        jButtonCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonCursos.setBorder(null);
        jButtonCursos.setBorderPainted(false);
        jButtonCursos.setContentAreaFilled(false);
        jButtonCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCursos.setRequestFocusEnabled(false);
        jButtonCursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonCursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonCursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCursosMouseClicked(evt);
            }
        });
        jButtonCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursosActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonCursos);
        jButtonCursos.setBounds(200, 190, 60, 50);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aulas");
        jLabel6.setToolTipText("");
        jPanelLogin.add(jLabel6);
        jLabel6.setBounds(20, 260, 170, 28);

        jButtonAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonAulas.setBorder(null);
        jButtonAulas.setBorderPainted(false);
        jButtonAulas.setContentAreaFilled(false);
        jButtonAulas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAulas.setRequestFocusEnabled(false);
        jButtonAulas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAulas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAulas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAulasMouseClicked(evt);
            }
        });
        jButtonAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAulasActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonAulas);
        jButtonAulas.setBounds(200, 250, 60, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Imparte");
        jLabel12.setToolTipText("");
        jPanelLogin.add(jLabel12);
        jLabel12.setBounds(20, 330, 170, 28);

        jButtonImparte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonImparte.setBorder(null);
        jButtonImparte.setBorderPainted(false);
        jButtonImparte.setContentAreaFilled(false);
        jButtonImparte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonImparte.setRequestFocusEnabled(false);
        jButtonImparte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonImparte.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonImparte.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonImparte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonImparteMouseClicked(evt);
            }
        });
        jButtonImparte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImparteActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonImparte);
        jButtonImparte.setBounds(200, 310, 60, 60);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Disponibilidad");
        jLabel13.setToolTipText("");
        jPanelLogin.add(jLabel13);
        jLabel13.setBounds(20, 390, 170, 28);

        jButtonDisponibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonDisponibilidad.setBorder(null);
        jButtonDisponibilidad.setBorderPainted(false);
        jButtonDisponibilidad.setContentAreaFilled(false);
        jButtonDisponibilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonDisponibilidad.setRequestFocusEnabled(false);
        jButtonDisponibilidad.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonDisponibilidad.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonDisponibilidad.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDisponibilidadMouseClicked(evt);
            }
        });
        jButtonDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisponibilidadActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonDisponibilidad);
        jButtonDisponibilidad.setBounds(200, 380, 60, 50);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Consultas Prolog");
        jLabel14.setToolTipText("");
        jPanelLogin.add(jLabel14);
        jLabel14.setBounds(20, 450, 190, 28);

        jButtonHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonHorario.setBorder(null);
        jButtonHorario.setBorderPainted(false);
        jButtonHorario.setContentAreaFilled(false);
        jButtonHorario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonHorario.setRequestFocusEnabled(false);
        jButtonHorario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonHorario.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonHorario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHorarioMouseClicked(evt);
            }
        });
        jButtonHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHorarioActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonHorario);
        jButtonHorario.setBounds(200, 440, 60, 50);

        getContentPane().add(jPanelLogin);
        jPanelLogin.setBounds(0, 0, 265, 600);

        jPanelHorarios.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelHorarios.setAlignmentX(0.0F);
        jPanelHorarios.setAlignmentY(0.0F);
        jPanelHorarios.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelHorarios.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Seleccione la lista de Cursos");
        jLabel19.setToolTipText("");
        jPanelHorarios.add(jLabel19);
        jLabel19.setBounds(40, 100, 330, 28);

        jTableCursosHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTableCursosHorario);

        jPanelHorarios.add(jScrollPane6);
        jScrollPane6.setBounds(40, 150, 452, 250);

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Configuración de Cursos \\n  para generar horarios");
        jPanelHorarios.add(jLabel26);
        jLabel26.setBounds(170, 430, 220, 40);

        jLabel45.setBackground(new java.awt.Color(255, 255, 255));
        jLabel45.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Nuevo");
        jPanelHorarios.add(jLabel45);
        jLabel45.setBounds(210, 470, 70, 40);

        jLabel46.setBackground(new java.awt.Color(255, 255, 255));
        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("Eliminar");
        jPanelHorarios.add(jLabel46);
        jLabel46.setBounds(210, 520, 70, 40);

        jButtonConfirmBill8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonConfirmBill8.setBorder(null);
        jButtonConfirmBill8.setBorderPainted(false);
        jButtonConfirmBill8.setContentAreaFilled(false);
        jButtonConfirmBill8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill8.setRequestFocusEnabled(false);
        jButtonConfirmBill8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill8.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill8MouseClicked(evt);
            }
        });
        jButtonConfirmBill8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill8ActionPerformed(evt);
            }
        });
        jPanelHorarios.add(jButtonConfirmBill8);
        jButtonConfirmBill8.setBounds(290, 520, 40, 40);

        jButtonConfirmBill9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonConfirmBill9.setBorder(null);
        jButtonConfirmBill9.setBorderPainted(false);
        jButtonConfirmBill9.setContentAreaFilled(false);
        jButtonConfirmBill9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill9.setRequestFocusEnabled(false);
        jButtonConfirmBill9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill9.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill9MouseClicked(evt);
            }
        });
        jButtonConfirmBill9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill9ActionPerformed(evt);
            }
        });
        jPanelHorarios.add(jButtonConfirmBill9);
        jButtonConfirmBill9.setBounds(290, 470, 40, 40);

        CD_Cliente5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelHorarios.add(CD_Cliente5);
        CD_Cliente5.setBounds(140, 410, 270, 180);

        jButtonClose6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose6.setBorder(null);
        jButtonClose6.setBorderPainted(false);
        jButtonClose6.setContentAreaFilled(false);
        jButtonClose6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose6.setRequestFocusEnabled(false);
        jButtonClose6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose6MouseClicked(evt);
            }
        });
        jButtonClose6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose6ActionPerformed(evt);
            }
        });
        jPanelHorarios.add(jButtonClose6);
        jButtonClose6.setBounds(470, 20, 51, 51);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel20.setText("jLabel2");
        jPanelHorarios.add(jLabel20);
        jLabel20.setBounds(0, 0, 535, 600);

        jCheckBox1.setText("jCheckBox1");
        jPanelHorarios.add(jCheckBox1);
        jCheckBox1.setBounds(430, 450, 81, 23);

        getContentPane().add(jPanelHorarios);
        jPanelHorarios.setBounds(265, 0, 535, 600);

        jPanelProfesor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelProfesor.setAlignmentX(0.0F);
        jPanelProfesor.setAlignmentY(0.0F);
        jPanelProfesor.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelProfesor.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lista de Profesores");
        jLabel7.setToolTipText("");
        jPanelProfesor.add(jLabel7);
        jLabel7.setBounds(40, 100, 230, 28);

        jTableProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTableProfesor);

        jPanelProfesor.add(jScrollPane7);
        jScrollPane7.setBounds(40, 150, 452, 250);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Configuración de Profesores");
        jPanelProfesor.add(jLabel21);
        jLabel21.setBounds(170, 430, 220, 17);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nuevo");
        jPanelProfesor.add(jLabel35);
        jLabel35.setBounds(210, 470, 70, 40);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Eliminar");
        jPanelProfesor.add(jLabel36);
        jLabel36.setBounds(210, 520, 70, 40);

        jButtonConfirmBill4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonConfirmBill4.setBorder(null);
        jButtonConfirmBill4.setBorderPainted(false);
        jButtonConfirmBill4.setContentAreaFilled(false);
        jButtonConfirmBill4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill4.setRequestFocusEnabled(false);
        jButtonConfirmBill4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill4MouseClicked(evt);
            }
        });
        jButtonConfirmBill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill4ActionPerformed(evt);
            }
        });
        jPanelProfesor.add(jButtonConfirmBill4);
        jButtonConfirmBill4.setBounds(290, 520, 40, 40);

        jButtonConfirmBill5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonConfirmBill5.setBorder(null);
        jButtonConfirmBill5.setBorderPainted(false);
        jButtonConfirmBill5.setContentAreaFilled(false);
        jButtonConfirmBill5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill5.setRequestFocusEnabled(false);
        jButtonConfirmBill5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill5MouseClicked(evt);
            }
        });
        jButtonConfirmBill5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill5ActionPerformed(evt);
            }
        });
        jPanelProfesor.add(jButtonConfirmBill5);
        jButtonConfirmBill5.setBounds(290, 470, 40, 40);

        CD_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelProfesor.add(CD_Cliente);
        CD_Cliente.setBounds(140, 410, 270, 180);

        jButtonClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose1.setBorder(null);
        jButtonClose1.setBorderPainted(false);
        jButtonClose1.setContentAreaFilled(false);
        jButtonClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose1.setRequestFocusEnabled(false);
        jButtonClose1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose1MouseClicked(evt);
            }
        });
        jButtonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose1ActionPerformed(evt);
            }
        });
        jPanelProfesor.add(jButtonClose1);
        jButtonClose1.setBounds(470, 20, 51, 51);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanelProfesor.add(jLabel2);
        jLabel2.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelProfesor);
        jPanelProfesor.setBounds(265, 0, 535, 600);

        jPanelCursos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelCursos.setAlignmentX(0.0F);
        jPanelCursos.setAlignmentY(0.0F);
        jPanelCursos.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelCursos.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lista de Cursos");
        jLabel8.setToolTipText("");
        jPanelCursos.add(jLabel8);
        jLabel8.setBounds(40, 100, 230, 28);

        jTableCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCursos);

        jPanelCursos.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 452, 250);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Configuración de Cursos");
        jPanelCursos.add(jLabel22);
        jLabel22.setBounds(170, 430, 220, 17);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Nuevo");
        jPanelCursos.add(jLabel37);
        jLabel37.setBounds(210, 470, 70, 40);

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Eliminar");
        jPanelCursos.add(jLabel38);
        jLabel38.setBounds(210, 520, 70, 40);

        jButtonConfirmBill6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonConfirmBill6.setBorder(null);
        jButtonConfirmBill6.setBorderPainted(false);
        jButtonConfirmBill6.setContentAreaFilled(false);
        jButtonConfirmBill6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill6.setRequestFocusEnabled(false);
        jButtonConfirmBill6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill6MouseClicked(evt);
            }
        });
        jButtonConfirmBill6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill6ActionPerformed(evt);
            }
        });
        jPanelCursos.add(jButtonConfirmBill6);
        jButtonConfirmBill6.setBounds(290, 520, 40, 40);

        jButtonConfirmBill7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonConfirmBill7.setBorder(null);
        jButtonConfirmBill7.setBorderPainted(false);
        jButtonConfirmBill7.setContentAreaFilled(false);
        jButtonConfirmBill7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill7.setRequestFocusEnabled(false);
        jButtonConfirmBill7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill7MouseClicked(evt);
            }
        });
        jButtonConfirmBill7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill7ActionPerformed(evt);
            }
        });
        jPanelCursos.add(jButtonConfirmBill7);
        jButtonConfirmBill7.setBounds(290, 470, 40, 40);

        CD_Cliente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelCursos.add(CD_Cliente1);
        CD_Cliente1.setBounds(140, 410, 270, 180);

        jButtonClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose2.setBorder(null);
        jButtonClose2.setBorderPainted(false);
        jButtonClose2.setContentAreaFilled(false);
        jButtonClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose2.setRequestFocusEnabled(false);
        jButtonClose2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose2MouseClicked(evt);
            }
        });
        jButtonClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose2ActionPerformed(evt);
            }
        });
        jPanelCursos.add(jButtonClose2);
        jButtonClose2.setBounds(470, 20, 51, 51);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jPanelCursos.add(jLabel9);
        jLabel9.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelCursos);
        jPanelCursos.setBounds(265, 0, 535, 600);

        jPanelAulas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelAulas.setAlignmentX(0.0F);
        jPanelAulas.setAlignmentY(0.0F);
        jPanelAulas.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelAulas.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lista de Aulas");
        jLabel10.setToolTipText("");
        jPanelAulas.add(jLabel10);
        jLabel10.setBounds(40, 100, 230, 28);

        jTableAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableAulas);

        jPanelAulas.add(jScrollPane3);
        jScrollPane3.setBounds(40, 150, 452, 250);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Configuración de Aulas");
        jPanelAulas.add(jLabel23);
        jLabel23.setBounds(170, 430, 220, 17);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Nuevo");
        jPanelAulas.add(jLabel39);
        jLabel39.setBounds(210, 470, 70, 40);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Eliminar");
        jPanelAulas.add(jLabel40);
        jLabel40.setBounds(210, 520, 70, 40);

        jButtonEliminarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonEliminarAula.setBorder(null);
        jButtonEliminarAula.setBorderPainted(false);
        jButtonEliminarAula.setContentAreaFilled(false);
        jButtonEliminarAula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEliminarAula.setRequestFocusEnabled(false);
        jButtonEliminarAula.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarAula.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarAula.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarAulaMouseClicked(evt);
            }
        });
        jButtonEliminarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAulaActionPerformed(evt);
            }
        });
        jPanelAulas.add(jButtonEliminarAula);
        jButtonEliminarAula.setBounds(290, 520, 40, 40);

        jButtonAgregarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonAgregarAula.setBorder(null);
        jButtonAgregarAula.setBorderPainted(false);
        jButtonAgregarAula.setContentAreaFilled(false);
        jButtonAgregarAula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAgregarAula.setRequestFocusEnabled(false);
        jButtonAgregarAula.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarAula.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarAula.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarAulaMouseClicked(evt);
            }
        });
        jButtonAgregarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAulaActionPerformed(evt);
            }
        });
        jPanelAulas.add(jButtonAgregarAula);
        jButtonAgregarAula.setBounds(290, 470, 40, 40);

        CD_Cliente2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelAulas.add(CD_Cliente2);
        CD_Cliente2.setBounds(140, 410, 270, 180);

        jButtonClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose3.setBorder(null);
        jButtonClose3.setBorderPainted(false);
        jButtonClose3.setContentAreaFilled(false);
        jButtonClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose3.setRequestFocusEnabled(false);
        jButtonClose3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose3MouseClicked(evt);
            }
        });
        jButtonClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose3ActionPerformed(evt);
            }
        });
        jPanelAulas.add(jButtonClose3);
        jButtonClose3.setBounds(470, 20, 51, 51);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        jPanelAulas.add(jLabel11);
        jLabel11.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelAulas);
        jPanelAulas.setBounds(265, 0, 535, 600);

        jPanelImparte.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelImparte.setAlignmentX(0.0F);
        jPanelImparte.setAlignmentY(0.0F);
        jPanelImparte.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelImparte.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Profesores - Cursos");
        jLabel15.setToolTipText("");
        jPanelImparte.add(jLabel15);
        jLabel15.setBounds(40, 100, 230, 28);

        jTableImparte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableImparte);

        jPanelImparte.add(jScrollPane4);
        jScrollPane4.setBounds(40, 150, 452, 250);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Configuración de Relaciones");
        jPanelImparte.add(jLabel24);
        jLabel24.setBounds(170, 430, 220, 17);

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Nuevo");
        jPanelImparte.add(jLabel41);
        jLabel41.setBounds(210, 470, 70, 40);

        jLabel42.setBackground(new java.awt.Color(255, 255, 255));
        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Eliminar");
        jPanelImparte.add(jLabel42);
        jLabel42.setBounds(210, 520, 70, 40);

        jButtonEliminarRelacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonEliminarRelacion.setBorder(null);
        jButtonEliminarRelacion.setBorderPainted(false);
        jButtonEliminarRelacion.setContentAreaFilled(false);
        jButtonEliminarRelacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEliminarRelacion.setRequestFocusEnabled(false);
        jButtonEliminarRelacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarRelacion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarRelacion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarRelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarRelacionMouseClicked(evt);
            }
        });
        jButtonEliminarRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarRelacionActionPerformed(evt);
            }
        });
        jPanelImparte.add(jButtonEliminarRelacion);
        jButtonEliminarRelacion.setBounds(290, 520, 40, 40);

        jButtonAgregarRelacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonAgregarRelacion.setBorder(null);
        jButtonAgregarRelacion.setBorderPainted(false);
        jButtonAgregarRelacion.setContentAreaFilled(false);
        jButtonAgregarRelacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAgregarRelacion.setRequestFocusEnabled(false);
        jButtonAgregarRelacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarRelacion.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarRelacion.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarRelacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarRelacionMouseClicked(evt);
            }
        });
        jButtonAgregarRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarRelacionActionPerformed(evt);
            }
        });
        jPanelImparte.add(jButtonAgregarRelacion);
        jButtonAgregarRelacion.setBounds(290, 470, 40, 40);

        CD_Cliente3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelImparte.add(CD_Cliente3);
        CD_Cliente3.setBounds(140, 410, 270, 180);

        jButtonClose4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose4.setBorder(null);
        jButtonClose4.setBorderPainted(false);
        jButtonClose4.setContentAreaFilled(false);
        jButtonClose4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose4.setRequestFocusEnabled(false);
        jButtonClose4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose4MouseClicked(evt);
            }
        });
        jButtonClose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose4ActionPerformed(evt);
            }
        });
        jPanelImparte.add(jButtonClose4);
        jButtonClose4.setBounds(470, 20, 51, 51);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel16.setText("jLabel2");
        jPanelImparte.add(jLabel16);
        jLabel16.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelImparte);
        jPanelImparte.setBounds(265, 0, 535, 600);

        jPanelDisponibilidad.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelDisponibilidad.setAlignmentX(0.0F);
        jPanelDisponibilidad.setAlignmentY(0.0F);
        jPanelDisponibilidad.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelDisponibilidad.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Profesores - Disponibilidad");
        jLabel17.setToolTipText("");
        jPanelDisponibilidad.add(jLabel17);
        jLabel17.setBounds(40, 100, 360, 28);

        jTableDisponibilidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableDisponibilidad);

        jPanelDisponibilidad.add(jScrollPane5);
        jScrollPane5.setBounds(40, 150, 452, 250);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Configuración de Relaciones");
        jPanelDisponibilidad.add(jLabel25);
        jLabel25.setBounds(170, 430, 220, 17);

        jLabel43.setBackground(new java.awt.Color(255, 255, 255));
        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Nuevo");
        jPanelDisponibilidad.add(jLabel43);
        jLabel43.setBounds(210, 470, 70, 40);

        jLabel44.setBackground(new java.awt.Color(255, 255, 255));
        jLabel44.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Eliminar");
        jPanelDisponibilidad.add(jLabel44);
        jLabel44.setBounds(210, 520, 70, 40);

        jButtonEliminarRelacionDisponibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonEliminarRelacionDisponibilidad.setBorder(null);
        jButtonEliminarRelacionDisponibilidad.setBorderPainted(false);
        jButtonEliminarRelacionDisponibilidad.setContentAreaFilled(false);
        jButtonEliminarRelacionDisponibilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEliminarRelacionDisponibilidad.setRequestFocusEnabled(false);
        jButtonEliminarRelacionDisponibilidad.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarRelacionDisponibilidad.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarRelacionDisponibilidad.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarRelacionDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarRelacionDisponibilidadMouseClicked(evt);
            }
        });
        jButtonEliminarRelacionDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarRelacionDisponibilidadActionPerformed(evt);
            }
        });
        jPanelDisponibilidad.add(jButtonEliminarRelacionDisponibilidad);
        jButtonEliminarRelacionDisponibilidad.setBounds(290, 520, 40, 40);

        jButtonAgregarRelacionDisponibilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonAgregarRelacionDisponibilidad.setBorder(null);
        jButtonAgregarRelacionDisponibilidad.setBorderPainted(false);
        jButtonAgregarRelacionDisponibilidad.setContentAreaFilled(false);
        jButtonAgregarRelacionDisponibilidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAgregarRelacionDisponibilidad.setRequestFocusEnabled(false);
        jButtonAgregarRelacionDisponibilidad.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarRelacionDisponibilidad.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarRelacionDisponibilidad.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarRelacionDisponibilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarRelacionDisponibilidadMouseClicked(evt);
            }
        });
        jButtonAgregarRelacionDisponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarRelacionDisponibilidadActionPerformed(evt);
            }
        });
        jPanelDisponibilidad.add(jButtonAgregarRelacionDisponibilidad);
        jButtonAgregarRelacionDisponibilidad.setBounds(290, 470, 40, 40);

        CD_Cliente4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelDisponibilidad.add(CD_Cliente4);
        CD_Cliente4.setBounds(140, 410, 270, 180);

        jButtonClose5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose5.setBorder(null);
        jButtonClose5.setBorderPainted(false);
        jButtonClose5.setContentAreaFilled(false);
        jButtonClose5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose5.setRequestFocusEnabled(false);
        jButtonClose5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose5MouseClicked(evt);
            }
        });
        jButtonClose5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose5ActionPerformed(evt);
            }
        });
        jPanelDisponibilidad.add(jButtonClose5);
        jButtonClose5.setBounds(470, 20, 51, 51);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel18.setText("jLabel2");
        jPanelDisponibilidad.add(jLabel18);
        jLabel18.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelDisponibilidad);
        jPanelDisponibilidad.setBounds(265, 0, 535, 600);

        jButtonOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off1.png"))); // NOI18N
        jButtonOff.setBorder(null);
        jButtonOff.setBorderPainted(false);
        jButtonOff.setContentAreaFilled(false);
        jButtonOff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonOff.setRequestFocusEnabled(false);
        jButtonOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off2.png"))); // NOI18N
        jButtonOff.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/off2.png"))); // NOI18N
        jButtonOff.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/off2.png"))); // NOI18N
        jButtonOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOffMouseClicked(evt);
            }
        });
        jButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOffActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOff);
        jButtonOff.setBounds(740, 20, 41, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOffMouseClicked
        Singleton.getInstance().closeSystem();
    }//GEN-LAST:event_jButtonOffMouseClicked

    private void jButtonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOffActionPerformed

    private void jButtonProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProfesoresMouseClicked
       
    }//GEN-LAST:event_jButtonProfesoresMouseClicked

    private void jButtonProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfesoresActionPerformed
        cerrarPaneles();
        datosProfesor();
    }//GEN-LAST:event_jButtonProfesoresActionPerformed

    private void jButtonCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCursosMouseClicked
        
    }//GEN-LAST:event_jButtonCursosMouseClicked

    private void jButtonCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCursosActionPerformed
        cerrarPaneles();
        datosCursos();
    }//GEN-LAST:event_jButtonCursosActionPerformed

    private void jButtonAulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAulasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAulasMouseClicked

    private void jButtonAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAulasActionPerformed
        cerrarPaneles();
        datosAulas();
    }//GEN-LAST:event_jButtonAulasActionPerformed

    private void jButtonClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose1MouseClicked

    }//GEN-LAST:event_jButtonClose1MouseClicked

    private void jButtonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose1ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose1ActionPerformed

    private void jButtonConfirmBill4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill4MouseClicked

    }//GEN-LAST:event_jButtonConfirmBill4MouseClicked

    private void jButtonConfirmBill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill4ActionPerformed
        if(!jTableProfesor.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableProfesor.getValueAt(jTableProfesor.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminar(id, "Profesor")){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosProfesor();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        }   
    }//GEN-LAST:event_jButtonConfirmBill4ActionPerformed

    private void jButtonConfirmBill5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill5MouseClicked

    }//GEN-LAST:event_jButtonConfirmBill5MouseClicked

    private void jButtonConfirmBill5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill5ActionPerformed
        WindowsAgregarProfesor wr = new WindowsAgregarProfesor(this);
        wr.show();
        
    }//GEN-LAST:event_jButtonConfirmBill5ActionPerformed

    private void jButtonConfirmBill6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill6MouseClicked

    private void jButtonConfirmBill6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill6ActionPerformed
        if(!jTableCursos.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableCursos.getValueAt(jTableCursos.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminar(id, "Curso")){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosCursos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        } 
    }//GEN-LAST:event_jButtonConfirmBill6ActionPerformed

    private void jButtonConfirmBill7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill7MouseClicked

    private void jButtonConfirmBill7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill7ActionPerformed
        WindowsAgregarCurso wc = new WindowsAgregarCurso(this);
        wc.setVisible(true);
    }//GEN-LAST:event_jButtonConfirmBill7ActionPerformed

    private void jButtonClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose2MouseClicked

    private void jButtonClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose2ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose2ActionPerformed

    private void jButtonEliminarAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarAulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarAulaMouseClicked

    private void jButtonEliminarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAulaActionPerformed
        if(!jTableAulas.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableAulas.getValueAt(jTableAulas.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminar(id, "Aula")){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosAulas();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        } 
    }//GEN-LAST:event_jButtonEliminarAulaActionPerformed

    private void jButtonAgregarAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarAulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarAulaMouseClicked

    private void jButtonAgregarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAulaActionPerformed
        WindowsAgregarAula wa = new WindowsAgregarAula(this);
        wa.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarAulaActionPerformed

    private void jButtonClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose3MouseClicked

    private void jButtonClose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose3ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose3ActionPerformed

    private void jButtonImparteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImparteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonImparteMouseClicked

    private void jButtonImparteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImparteActionPerformed
        cerrarPaneles();
        datosImparte();
    }//GEN-LAST:event_jButtonImparteActionPerformed

    private void jButtonDisponibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDisponibilidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDisponibilidadMouseClicked

    private void jButtonDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisponibilidadActionPerformed
        cerrarPaneles();
        datosDisponibilidad();
    }//GEN-LAST:event_jButtonDisponibilidadActionPerformed

    private void jButtonHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHorarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHorarioMouseClicked

    private void jButtonHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHorarioActionPerformed
        cerrarPaneles();
        datosHorarios();
        
    }//GEN-LAST:event_jButtonHorarioActionPerformed

    private void jButtonEliminarRelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarRelacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarRelacionMouseClicked

    private void jButtonEliminarRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarRelacionActionPerformed
        if(!jTableImparte.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableImparte.getValueAt(jTableImparte.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminar(id, "Imparte")){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosImparte();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        } 
    }//GEN-LAST:event_jButtonEliminarRelacionActionPerformed

    private void jButtonAgregarRelacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarRelacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarRelacionMouseClicked

    private void jButtonAgregarRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarRelacionActionPerformed
        WindowsAgregarImparte wi = new WindowsAgregarImparte(this);
        wi.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarRelacionActionPerformed

    private void jButtonClose4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose4MouseClicked

    private void jButtonClose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose4ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose4ActionPerformed

    private void jButtonEliminarRelacionDisponibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarRelacionDisponibilidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarRelacionDisponibilidadMouseClicked

    private void jButtonEliminarRelacionDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarRelacionDisponibilidadActionPerformed
        if(!jTableDisponibilidad.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableDisponibilidad.getValueAt(jTableDisponibilidad.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminar(id, "Disponibilidad")){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosImparte();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        } 
    }//GEN-LAST:event_jButtonEliminarRelacionDisponibilidadActionPerformed

    private void jButtonAgregarRelacionDisponibilidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarRelacionDisponibilidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarRelacionDisponibilidadMouseClicked

    private void jButtonAgregarRelacionDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarRelacionDisponibilidadActionPerformed
        WindowsAgregarDisponibilidad w = new WindowsAgregarDisponibilidad(this);
        w.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarRelacionDisponibilidadActionPerformed

    private void jButtonClose5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose5MouseClicked

    private void jButtonClose5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose5ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose5ActionPerformed

    private void jButtonConfirmBill8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill8MouseClicked

    private void jButtonConfirmBill8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill8ActionPerformed

    private void jButtonConfirmBill9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill9MouseClicked

    private void jButtonConfirmBill9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill9ActionPerformed

    private void jButtonClose6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose6MouseClicked

    private void jButtonClose6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose6ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose6ActionPerformed
    
    protected void cerrarPaneles() {
        jPanelProfesor.setVisible(false);
        jPanelCursos.setVisible(false);
        jPanelAulas.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelDisponibilidad.setVisible(false);
        jPanelHorarios.setVisible(false);
    }
    
    protected String datosProfesor(){
        String sql = "SELECT id, nombre, apellidos, cedula FROM Profesor WHERE activo = 'T';";
        jTableProfesor.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelProfesor.setVisible(true);
        return  "";
    }
    
    protected String datosCursos(){
        String sql = "SELECT id, nombre, asignatura, creditos,semestre, cantidad_dias  FROM Curso WHERE activo = 'T';";
        jTableCursos.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelCursos.setVisible(true);
        return  "";
    }
    
    protected String datosHorarios(){
        String sql = "SELECT id, nombre, asignatura, creditos,semestre, cantidad_dias  FROM Curso WHERE activo = 'T';";
        jTableCursosHorario.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelHorarios.setVisible(true);
        return  "";
    }
    
    protected String datosAulas(){
        String sql = "SELECT id, nombre, capacidad, tipo FROM Aula WHERE activo = 'T';";
        jTableAulas.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelAulas.setVisible(true);
        return  "";
    }
    
    protected String datosImparte(){
        String sql =    " SELECT " +
                        " Imparte.id AS id, " +
                        " Profesor.nombre, Profesor.apellidos "+       
                        " AS apellido, " +
                        " Curso.nombre" +
                        " AS curso " +
                        " FROM " +
                        " Imparte " +
                        " INNER JOIN Profesor ON Profesor.id = Imparte.profesor_id " +
                        " INNER JOIN Curso ON Curso.id = Imparte.curso_id " +
                        " WHERE Imparte.activo = 'T';";
        
        jTableImparte.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelImparte.setVisible(true);
        return "";
    }
    
    protected String datosDisponibilidad(){
        String sql =    " SELECT Disponibilidad.id, Profesor.nombre, Profesor.apellidos, Dia.dia FROM Disponibilidad \n" +
                        " INNER JOIN Dia ON Dia.id = Disponibilidad.dia_id \n" +
                        " INNER JOIN Profesor ON Profesor.id = Disponibilidad.profesor_id \n" +
                        " WHERE Disponibilidad.activo = 'T' ORDER BY Profesor.nombre; ";
        jTableDisponibilidad.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelDisponibilidad.setVisible(true);
        return  "";
    }
    
    protected void updateTable(){
        jTableProfesor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableProfesor.setAutoCreateRowSorter(true);
        
        jTableAulas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableAulas.setAutoCreateRowSorter(true);
        
        jTableCursos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableCursos.setAutoCreateRowSorter(true);
        
        jTableImparte.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableImparte.setAutoCreateRowSorter(true);
        
        jTableDisponibilidad.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableDisponibilidad.setAutoCreateRowSorter(true);
        
        jTableCursosHorario.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTableCursosHorario.setAutoCreateRowSorter(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowsMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CD_Cliente;
    private javax.swing.JLabel CD_Cliente1;
    private javax.swing.JLabel CD_Cliente2;
    private javax.swing.JLabel CD_Cliente3;
    private javax.swing.JLabel CD_Cliente4;
    private javax.swing.JLabel CD_Cliente5;
    private javax.swing.JButton jButtonAgregarAula;
    private javax.swing.JButton jButtonAgregarRelacion;
    private javax.swing.JButton jButtonAgregarRelacionDisponibilidad;
    private javax.swing.JButton jButtonAulas;
    private javax.swing.JButton jButtonClose1;
    private javax.swing.JButton jButtonClose2;
    private javax.swing.JButton jButtonClose3;
    private javax.swing.JButton jButtonClose4;
    private javax.swing.JButton jButtonClose5;
    private javax.swing.JButton jButtonClose6;
    private javax.swing.JButton jButtonConfirmBill4;
    private javax.swing.JButton jButtonConfirmBill5;
    private javax.swing.JButton jButtonConfirmBill6;
    private javax.swing.JButton jButtonConfirmBill7;
    private javax.swing.JButton jButtonConfirmBill8;
    private javax.swing.JButton jButtonConfirmBill9;
    private javax.swing.JButton jButtonCursos;
    private javax.swing.JButton jButtonDisponibilidad;
    private javax.swing.JButton jButtonEliminarAula;
    private javax.swing.JButton jButtonEliminarRelacion;
    private javax.swing.JButton jButtonEliminarRelacionDisponibilidad;
    private javax.swing.JButton jButtonHorario;
    private javax.swing.JButton jButtonImparte;
    private javax.swing.JButton jButtonOff;
    private javax.swing.JButton jButtonProfesores;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelAulas;
    private javax.swing.JPanel jPanelCursos;
    private javax.swing.JPanel jPanelDisponibilidad;
    private javax.swing.JPanel jPanelHorarios;
    private javax.swing.JPanel jPanelImparte;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelProfesor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTableAulas;
    private javax.swing.JTable jTableCursos;
    private javax.swing.JTable jTableCursosHorario;
    private javax.swing.JTable jTableDisponibilidad;
    private javax.swing.JTable jTableImparte;
    private javax.swing.JTable jTableProfesor;
    // End of variables declaration//GEN-END:variables

    private Boolean cargarDatosListas() {
        try {
            SQLite.getInstance().obtenerAula();
            SQLite.getInstance().obtenerProfesor();
            SQLite.getInstance().obtenerCurso();
            SQLite.getInstance().obtenerDias();
            SQLite.getInstance().obtenerLeccion();
            SQLite.getInstance().obtenerDisponibilidad();
            SQLite.getInstance().obtenerImparte();
            SQLite.getInstance().obtenerHorario();
            return true;
        } catch (Exception e) {
            System.out.println("Error = "  + e);
            return false;
        }
        
    }

 
}
