/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;


import backend.Metodos;
import database.SQLite;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Baxi
 */
public class WindowsCRUD extends javax.swing.JFrame {

    /**
     * Creates new form W_Main
     */
    public WindowsCRUD() {
        initComponents();
        this.setSize(800,600);
        setLocationRelativeTo(null);
        cerrarPaneles();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonAulas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonProfesores = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonCursos = new javax.swing.JButton();
        jPanelAulas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAulas = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jButtonEliminarAula = new javax.swing.JButton();
        jButtonAgregarAula = new javax.swing.JButton();
        CD_Cliente2 = new javax.swing.JLabel();
        jButtonClose3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanelProfesor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfesor = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButtonConfirmBill4 = new javax.swing.JButton();
        jButtonConfirmBill5 = new javax.swing.JButton();
        CD_Cliente = new javax.swing.JLabel();
        jButtonClose1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelCursos = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCursos = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButtonConfirmBill6 = new javax.swing.JButton();
        jButtonConfirmBill7 = new javax.swing.JButton();
        CD_Cliente1 = new javax.swing.JLabel();
        jButtonClose2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonOff = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanelLogin.setBackground(new java.awt.Color(0, 0, 0));
        jPanelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), java.awt.Color.white));
        jPanelLogin.setToolTipText("");
        jPanelLogin.setAlignmentX(0.0F);
        jPanelLogin.setAlignmentY(0.0F);
        jPanelLogin.setMaximumSize(new java.awt.Dimension(265, 600));
        jPanelLogin.setMinimumSize(new java.awt.Dimension(265, 600));
        jPanelLogin.setName("panelLogin"); // NOI18N
        jPanelLogin.setPreferredSize(new java.awt.Dimension(265, 600));
        jPanelLogin.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 148, 148));
        jLabel3.setText("Proyecto 3 & 4");
        jLabel3.setToolTipText("");
        jPanelLogin.add(jLabel3);
        jLabel3.setBounds(20, 30, 230, 42);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aulas");
        jLabel6.setToolTipText("");
        jPanelLogin.add(jLabel6);
        jLabel6.setBounds(20, 260, 170, 28);

        jButtonAulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonAulas.setBorder(null);
        jButtonAulas.setBorderPainted(false);
        jButtonAulas.setContentAreaFilled(false);
        jButtonAulas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAulas.setRequestFocusEnabled(false);
        jButtonAulas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAulas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAulas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAulas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAulasMouseClicked(evt);
            }
        });
        jButtonAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAulasActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonAulas);
        jButtonAulas.setBounds(200, 250, 60, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Profesores");
        jLabel5.setToolTipText("");
        jPanelLogin.add(jLabel5);
        jLabel5.setBounds(20, 140, 170, 28);

        jButtonProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonProfesores.setBorder(null);
        jButtonProfesores.setBorderPainted(false);
        jButtonProfesores.setContentAreaFilled(false);
        jButtonProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonProfesores.setRequestFocusEnabled(false);
        jButtonProfesores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonProfesores.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonProfesores.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonProfesoresMouseClicked(evt);
            }
        });
        jButtonProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfesoresActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonProfesores);
        jButtonProfesores.setBounds(200, 120, 60, 60);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cursos");
        jLabel4.setToolTipText("");
        jPanelLogin.add(jLabel4);
        jLabel4.setBounds(20, 200, 170, 28);

        jButtonCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entrar.png"))); // NOI18N
        jButtonCursos.setBorder(null);
        jButtonCursos.setBorderPainted(false);
        jButtonCursos.setContentAreaFilled(false);
        jButtonCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCursos.setRequestFocusEnabled(false);
        jButtonCursos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonCursos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonCursos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCursosMouseClicked(evt);
            }
        });
        jButtonCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCursosActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonCursos);
        jButtonCursos.setBounds(200, 190, 60, 50);

        getContentPane().add(jPanelLogin);
        jPanelLogin.setBounds(0, 0, 265, 600);

        jPanelAulas.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelAulas.setAlignmentX(0.0F);
        jPanelAulas.setAlignmentY(0.0F);
        jPanelAulas.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelAulas.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Lista de Aulas");
        jLabel10.setToolTipText("");
        jPanelAulas.add(jLabel10);
        jLabel10.setBounds(40, 100, 230, 28);

        jTableAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableAulas);

        jPanelAulas.add(jScrollPane3);
        jScrollPane3.setBounds(40, 150, 452, 250);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Configuración de Aulas");
        jPanelAulas.add(jLabel23);
        jLabel23.setBounds(170, 430, 220, 17);

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Nuevo");
        jPanelAulas.add(jLabel39);
        jLabel39.setBounds(210, 470, 70, 40);

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Eliminar");
        jPanelAulas.add(jLabel40);
        jLabel40.setBounds(210, 520, 70, 40);

        jButtonEliminarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonEliminarAula.setBorder(null);
        jButtonEliminarAula.setBorderPainted(false);
        jButtonEliminarAula.setContentAreaFilled(false);
        jButtonEliminarAula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEliminarAula.setRequestFocusEnabled(false);
        jButtonEliminarAula.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarAula.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarAula.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonEliminarAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarAulaMouseClicked(evt);
            }
        });
        jButtonEliminarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAulaActionPerformed(evt);
            }
        });
        jPanelAulas.add(jButtonEliminarAula);
        jButtonEliminarAula.setBounds(290, 520, 40, 40);

        jButtonAgregarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonAgregarAula.setBorder(null);
        jButtonAgregarAula.setBorderPainted(false);
        jButtonAgregarAula.setContentAreaFilled(false);
        jButtonAgregarAula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAgregarAula.setRequestFocusEnabled(false);
        jButtonAgregarAula.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarAula.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarAula.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonAgregarAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarAulaMouseClicked(evt);
            }
        });
        jButtonAgregarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAulaActionPerformed(evt);
            }
        });
        jPanelAulas.add(jButtonAgregarAula);
        jButtonAgregarAula.setBounds(290, 470, 40, 40);

        CD_Cliente2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelAulas.add(CD_Cliente2);
        CD_Cliente2.setBounds(140, 410, 270, 180);

        jButtonClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose3.setBorder(null);
        jButtonClose3.setBorderPainted(false);
        jButtonClose3.setContentAreaFilled(false);
        jButtonClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose3.setRequestFocusEnabled(false);
        jButtonClose3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose3MouseClicked(evt);
            }
        });
        jButtonClose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose3ActionPerformed(evt);
            }
        });
        jPanelAulas.add(jButtonClose3);
        jButtonClose3.setBounds(470, 20, 51, 51);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel11.setText("jLabel2");
        jPanelAulas.add(jLabel11);
        jLabel11.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelAulas);
        jPanelAulas.setBounds(265, 0, 535, 600);

        jPanelProfesor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelProfesor.setAlignmentX(0.0F);
        jPanelProfesor.setAlignmentY(0.0F);
        jPanelProfesor.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelProfesor.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Lista de Profesores");
        jLabel7.setToolTipText("");
        jPanelProfesor.add(jLabel7);
        jLabel7.setBounds(40, 100, 230, 28);

        jTableProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProfesor);

        jPanelProfesor.add(jScrollPane1);
        jScrollPane1.setBounds(40, 150, 452, 250);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Configuración de Profesores");
        jPanelProfesor.add(jLabel21);
        jLabel21.setBounds(170, 430, 220, 17);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nuevo");
        jPanelProfesor.add(jLabel35);
        jLabel35.setBounds(210, 470, 70, 40);

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Eliminar");
        jPanelProfesor.add(jLabel36);
        jLabel36.setBounds(210, 520, 70, 40);

        jButtonConfirmBill4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonConfirmBill4.setBorder(null);
        jButtonConfirmBill4.setBorderPainted(false);
        jButtonConfirmBill4.setContentAreaFilled(false);
        jButtonConfirmBill4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill4.setRequestFocusEnabled(false);
        jButtonConfirmBill4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill4MouseClicked(evt);
            }
        });
        jButtonConfirmBill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill4ActionPerformed(evt);
            }
        });
        jPanelProfesor.add(jButtonConfirmBill4);
        jButtonConfirmBill4.setBounds(290, 520, 40, 40);

        jButtonConfirmBill5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonConfirmBill5.setBorder(null);
        jButtonConfirmBill5.setBorderPainted(false);
        jButtonConfirmBill5.setContentAreaFilled(false);
        jButtonConfirmBill5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill5.setRequestFocusEnabled(false);
        jButtonConfirmBill5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill5MouseClicked(evt);
            }
        });
        jButtonConfirmBill5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill5ActionPerformed(evt);
            }
        });
        jPanelProfesor.add(jButtonConfirmBill5);
        jButtonConfirmBill5.setBounds(290, 470, 40, 40);

        CD_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelProfesor.add(CD_Cliente);
        CD_Cliente.setBounds(140, 410, 270, 180);

        jButtonClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose1.setBorder(null);
        jButtonClose1.setBorderPainted(false);
        jButtonClose1.setContentAreaFilled(false);
        jButtonClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose1.setRequestFocusEnabled(false);
        jButtonClose1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose1MouseClicked(evt);
            }
        });
        jButtonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose1ActionPerformed(evt);
            }
        });
        jPanelProfesor.add(jButtonClose1);
        jButtonClose1.setBounds(470, 20, 51, 51);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanelProfesor.add(jLabel2);
        jLabel2.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelProfesor);
        jPanelProfesor.setBounds(265, 0, 535, 600);

        jPanelCursos.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white));
        jPanelCursos.setAlignmentX(0.0F);
        jPanelCursos.setAlignmentY(0.0F);
        jPanelCursos.setPreferredSize(new java.awt.Dimension(535, 600));
        jPanelCursos.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lista de Cursos");
        jLabel8.setToolTipText("");
        jPanelCursos.add(jLabel8);
        jLabel8.setBounds(40, 100, 230, 28);

        jTableCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCursos);

        jPanelCursos.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 452, 250);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Configuración de Cursos");
        jPanelCursos.add(jLabel22);
        jLabel22.setBounds(170, 430, 220, 17);

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Nuevo");
        jPanelCursos.add(jLabel37);
        jLabel37.setBounds(210, 470, 70, 40);

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Eliminar");
        jPanelCursos.add(jLabel38);
        jLabel38.setBounds(210, 520, 70, 40);

        jButtonConfirmBill6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete1.png"))); // NOI18N
        jButtonConfirmBill6.setBorder(null);
        jButtonConfirmBill6.setBorderPainted(false);
        jButtonConfirmBill6.setContentAreaFilled(false);
        jButtonConfirmBill6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill6.setRequestFocusEnabled(false);
        jButtonConfirmBill6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete2.png"))); // NOI18N
        jButtonConfirmBill6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill6MouseClicked(evt);
            }
        });
        jButtonConfirmBill6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill6ActionPerformed(evt);
            }
        });
        jPanelCursos.add(jButtonConfirmBill6);
        jButtonConfirmBill6.setBounds(290, 520, 40, 40);

        jButtonConfirmBill7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add1.png"))); // NOI18N
        jButtonConfirmBill7.setBorder(null);
        jButtonConfirmBill7.setBorderPainted(false);
        jButtonConfirmBill7.setContentAreaFilled(false);
        jButtonConfirmBill7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonConfirmBill7.setRequestFocusEnabled(false);
        jButtonConfirmBill7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill7.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill7.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add2.png"))); // NOI18N
        jButtonConfirmBill7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonConfirmBill7MouseClicked(evt);
            }
        });
        jButtonConfirmBill7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmBill7ActionPerformed(evt);
            }
        });
        jPanelCursos.add(jButtonConfirmBill7);
        jButtonConfirmBill7.setBounds(290, 470, 40, 40);

        CD_Cliente1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jPanelCursos.add(CD_Cliente1);
        CD_Cliente1.setBounds(140, 410, 270, 180);

        jButtonClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose2.setBorder(null);
        jButtonClose2.setBorderPainted(false);
        jButtonClose2.setContentAreaFilled(false);
        jButtonClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose2.setRequestFocusEnabled(false);
        jButtonClose2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose2MouseClicked(evt);
            }
        });
        jButtonClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose2ActionPerformed(evt);
            }
        });
        jPanelCursos.add(jButtonClose2);
        jButtonClose2.setBounds(470, 20, 51, 51);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPanel.png"))); // NOI18N
        jLabel9.setText("jLabel2");
        jPanelCursos.add(jLabel9);
        jLabel9.setBounds(0, 0, 535, 600);

        getContentPane().add(jPanelCursos);
        jPanelCursos.setBounds(265, 0, 535, 600);

        jButtonOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off1.png"))); // NOI18N
        jButtonOff.setBorder(null);
        jButtonOff.setBorderPainted(false);
        jButtonOff.setContentAreaFilled(false);
        jButtonOff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonOff.setRequestFocusEnabled(false);
        jButtonOff.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/off2.png"))); // NOI18N
        jButtonOff.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/off2.png"))); // NOI18N
        jButtonOff.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/off2.png"))); // NOI18N
        jButtonOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOffMouseClicked(evt);
            }
        });
        jButtonOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOffActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOff);
        jButtonOff.setBounds(740, 20, 41, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOffMouseClicked
        Metodos.getInstance().closeSystem();
    }//GEN-LAST:event_jButtonOffMouseClicked

    private void jButtonOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOffActionPerformed

    private void jButtonProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonProfesoresMouseClicked
       
    }//GEN-LAST:event_jButtonProfesoresMouseClicked

    private void jButtonProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfesoresActionPerformed
        cerrarPaneles();
        datosProfesor();
        //String sql = "SELECT * FROM Profesor;";
        //jTableProfesor.setModel(SQLite.getInstance().executeSQL(sql));
        //jPanelProfesor.setVisible(true);
        
    }//GEN-LAST:event_jButtonProfesoresActionPerformed

    private void jButtonCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCursosMouseClicked
        
    }//GEN-LAST:event_jButtonCursosMouseClicked

    private void jButtonCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCursosActionPerformed
        cerrarPaneles();
        datosCursos();
    }//GEN-LAST:event_jButtonCursosActionPerformed

    private void jButtonAulasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAulasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAulasMouseClicked

    private void jButtonAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAulasActionPerformed
        cerrarPaneles();
        datosAulas();
    }//GEN-LAST:event_jButtonAulasActionPerformed

    private void jButtonClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose1MouseClicked

    }//GEN-LAST:event_jButtonClose1MouseClicked

    private void jButtonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose1ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose1ActionPerformed

    private void jButtonConfirmBill4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill4MouseClicked

    }//GEN-LAST:event_jButtonConfirmBill4MouseClicked

    private void jButtonConfirmBill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill4ActionPerformed
        if(!jTableProfesor.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableProfesor.getValueAt(jTableProfesor.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminarProfesor(id)){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosProfesor();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        }   
    }//GEN-LAST:event_jButtonConfirmBill4ActionPerformed

    private void jButtonConfirmBill5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill5MouseClicked

    }//GEN-LAST:event_jButtonConfirmBill5MouseClicked

    private void jButtonConfirmBill5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill5ActionPerformed
        WindowsProfesor wr = new WindowsProfesor(this);
        wr.show();
        
    }//GEN-LAST:event_jButtonConfirmBill5ActionPerformed

    private void jButtonConfirmBill6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill6MouseClicked

    private void jButtonConfirmBill6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill6ActionPerformed
        if(!jTableCursos.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableCursos.getValueAt(jTableCursos.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminarCurso(id)){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosCursos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        } 
    }//GEN-LAST:event_jButtonConfirmBill6ActionPerformed

    private void jButtonConfirmBill7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConfirmBill7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmBill7MouseClicked

    private void jButtonConfirmBill7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmBill7ActionPerformed
        WindowsCurso wc = new WindowsCurso(this);
        wc.setVisible(true);
    }//GEN-LAST:event_jButtonConfirmBill7ActionPerformed

    private void jButtonClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose2MouseClicked

    private void jButtonClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose2ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose2ActionPerformed

    private void jButtonEliminarAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarAulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarAulaMouseClicked

    private void jButtonEliminarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAulaActionPerformed
        if(!jTableAulas.getSelectionModel().isSelectionEmpty()){
            int id =(int) jTableAulas.getValueAt(jTableAulas.getSelectedRow(), 0);
            if(SQLite.getInstance().eliminarAula(id)){
                JOptionPane.showMessageDialog(null, "Eliminado");
                cerrarPaneles();
                datosAulas();
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar...");
            }
        } 
    }//GEN-LAST:event_jButtonEliminarAulaActionPerformed

    private void jButtonAgregarAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarAulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarAulaMouseClicked

    private void jButtonAgregarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAulaActionPerformed
        WindowsAula wa = new WindowsAula(this);
        wa.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarAulaActionPerformed

    private void jButtonClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonClose3MouseClicked

    private void jButtonClose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose3ActionPerformed
        cerrarPaneles();
    }//GEN-LAST:event_jButtonClose3ActionPerformed
    
    public void cerrarPaneles() {
        jPanelProfesor.setVisible(false);
        jPanelCursos.setVisible(false);
        jPanelAulas.setVisible(false);
    }
    
    public String datosProfesor(){
        String sql = "SELECT id, nombre, apellidos, cedula FROM Profesor WHERE activo = 'T';";
        jTableProfesor.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelProfesor.setVisible(true);
        return  "";
    }
    
    public String datosCursos(){
        String sql = "SELECT id, nombre, asignatura, creditos,semestre, cantidad_dias  FROM Curso WHERE activo = 'T';";
        jTableCursos.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelCursos.setVisible(true);
        return  "";
    }
    
    public String datosAulas(){
        String sql = "SELECT id, nombre, capacidad, tipo FROM Aula WHERE activo = 'T';";
        jTableAulas.setModel(SQLite.getInstance().executeSQL(sql));
        jPanelAulas.setVisible(true);
        return  "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowsCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowsCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowsCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowsCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowsCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CD_Cliente;
    private javax.swing.JLabel CD_Cliente1;
    private javax.swing.JLabel CD_Cliente2;
    private javax.swing.JButton jButtonAgregarAula;
    private javax.swing.JButton jButtonAulas;
    private javax.swing.JButton jButtonClose1;
    private javax.swing.JButton jButtonClose2;
    private javax.swing.JButton jButtonClose3;
    private javax.swing.JButton jButtonConfirmBill4;
    private javax.swing.JButton jButtonConfirmBill5;
    private javax.swing.JButton jButtonConfirmBill6;
    private javax.swing.JButton jButtonConfirmBill7;
    private javax.swing.JButton jButtonCursos;
    private javax.swing.JButton jButtonEliminarAula;
    private javax.swing.JButton jButtonOff;
    private javax.swing.JButton jButtonProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAulas;
    private javax.swing.JPanel jPanelCursos;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelProfesor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAulas;
    private javax.swing.JTable jTableCursos;
    private javax.swing.JTable jTableProfesor;
    // End of variables declaration//GEN-END:variables

 
}
