/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;



import backend.SingletonProlog;
import database.SQLite;
import entity.Curso;
import javax.swing.JOptionPane;
import patterns.Singleton;

/**
 *
 * @author Baxi
 */
public class WindowsModificarCurso extends javax.swing.JFrame {
    WindowsMenu wc;
    Curso c;
    
    public WindowsModificarCurso(WindowsMenu wm,Curso curso) {
        initComponents();
        this.setSize(450,250);
        setLocationRelativeTo(null);
        this.wc = wm;
        c = curso;
        jTextFieldNombre.setText(c.getNombre());
        jComboBoxSemestre.setSelectedIndex(c.getSemestre()-1);
        jComboBoxCreditos.setSelectedIndex(c.getCreditos()-1);
        jComboBoxDias.setSelectedIndex(c.getCantidadDias()-1);
        jComboBoxAsignatura.setSelectedItem(c.getAsignatura());
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButtonClose1 = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxSemestre = new javax.swing.JComboBox<>();
        jComboBoxAsignatura = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxCreditos = new javax.swing.JComboBox<>();
        jComboBoxDias = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jButtonAgregarCurso = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(467, 3));
        getContentPane().setLayout(null);

        jButtonClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close1.png"))); // NOI18N
        jButtonClose1.setBorder(null);
        jButtonClose1.setBorderPainted(false);
        jButtonClose1.setContentAreaFilled(false);
        jButtonClose1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClose1.setRequestFocusEnabled(false);
        jButtonClose1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close2.png"))); // NOI18N
        jButtonClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClose1MouseClicked(evt);
            }
        });
        jButtonClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClose1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose1);
        jButtonClose1.setBounds(370, 10, 70, 60);

        jLabelTitle.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Modificar curso");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(20, 10, 320, 28);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 50, 80, 30);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(160, 60, 140, 20);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Asignatura");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(60, 150, 80, 30);

        jComboBoxSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        getContentPane().add(jComboBoxSemestre);
        jComboBoxSemestre.setBounds(160, 90, 140, 20);

        jComboBoxAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "normal", "laboratorio" }));
        getContentPane().add(jComboBoxAsignatura);
        jComboBoxAsignatura.setBounds(160, 150, 140, 20);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Dias");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(60, 180, 80, 30);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Creditos");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(60, 120, 80, 30);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Semestre");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(60, 80, 80, 30);

        jComboBoxCreditos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(jComboBoxCreditos);
        jComboBoxCreditos.setBounds(160, 120, 140, 20);

        jComboBoxDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jComboBoxDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDias);
        jComboBoxDias.setBounds(160, 180, 140, 20);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Modificar");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(360, 150, 70, 30);

        jButtonAgregarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar.png"))); // NOI18N
        jButtonAgregarCurso.setBorder(null);
        jButtonAgregarCurso.setBorderPainted(false);
        jButtonAgregarCurso.setContentAreaFilled(false);
        jButtonAgregarCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAgregarCurso.setRequestFocusEnabled(false);
        jButtonAgregarCurso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAgregarCurso.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAgregarCurso.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/entrar2.png"))); // NOI18N
        jButtonAgregarCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAgregarCursoMouseClicked(evt);
            }
        });
        jButtonAgregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregarCurso);
        jButtonAgregarCurso.setBounds(350, 180, 80, 70);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hydrogen.jpg"))); // NOI18N
        bg.setMaximumSize(new java.awt.Dimension(450, 250));
        bg.setMinimumSize(new java.awt.Dimension(450, 250));
        bg.setPreferredSize(new java.awt.Dimension(450, 250));
        getContentPane().add(bg);
        bg.setBounds(0, 0, 450, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonAgregarCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgregarCursoMouseClicked
        
    }//GEN-LAST:event_jButtonAgregarCursoMouseClicked

    private void jButtonAgregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCursoActionPerformed
        if (!jTextFieldNombre.getText().isEmpty()) {
            try {
                String eliminar = "retract(" +Singleton.getInstance().buscarCurso(c.getId()).getDatos()+").";
                SingletonProlog.getInstance().consultaProlog(eliminar);
                
                SQLite.getInstance().modificarCurso(
                    c.getId(), 
                    jTextFieldNombre.getText(),
                    (String) jComboBoxAsignatura.getSelectedItem(), 
                    Integer.parseInt(jComboBoxCreditos.getSelectedItem().toString()),
                    Integer.parseInt(jComboBoxSemestre.getSelectedItem().toString()),
                    Integer.parseInt(jComboBoxDias.getSelectedItem().toString()));
                JOptionPane.showMessageDialog(null, "Curso actualizado correctamente!");

                Singleton.getInstance().buscarCurso(c.getId()).setNombre(jTextFieldNombre.getText());
                Singleton.getInstance().buscarCurso(c.getId()).setAsignatura((String) jComboBoxAsignatura.getSelectedItem());
                Singleton.getInstance().buscarCurso(c.getId()).setCreditos(Integer.parseInt(jComboBoxCreditos.getSelectedItem().toString()));
                Singleton.getInstance().buscarCurso(c.getId()).setSemestre(Integer.parseInt(jComboBoxSemestre.getSelectedItem().toString()));
                Singleton.getInstance().buscarCurso(c.getId()).setCantidadDias(Integer.parseInt(jComboBoxDias.getSelectedItem().toString()));
                
                SingletonProlog.getInstance().InsertarDatoEnMemoria(Singleton.getInstance().buscarCurso(c.getId()).getHecho());
                
                wc.cerrarPaneles();
                wc.datosCursos();
                this.dispose();
            } catch (Exception e) {
                System.out.println("\nError = " + e);
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre..!");
        }
    }//GEN-LAST:event_jButtonAgregarCursoActionPerformed

    private void jButtonClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClose1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButtonClose1MouseClicked

    private void jButtonClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClose1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonClose1ActionPerformed

    private void jComboBoxDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDiasActionPerformed


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgregarCurso;
    private javax.swing.JButton jButtonClose1;
    private javax.swing.JComboBox<String> jComboBoxAsignatura;
    private javax.swing.JComboBox<String> jComboBoxCreditos;
    private javax.swing.JComboBox<String> jComboBoxDias;
    private javax.swing.JComboBox<String> jComboBoxSemestre;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
